ServerName "Sentinel Mesh FTP"
ServerType standalone
DefaultServer on
Port 21
UseIPv6 off
Umask 022
MaxInstances 30
User proftpd
Group nogroup
RequireValidShell off
DefaultRoot /var/ftp
AllowOverwrite on
TransferLog /var/log/proftpd/xferlog
SystemLog /var/log/proftpd/proftpd.log

LoadModule mod_copy.c

<Anonymous /var/ftp>
  User ftpuser
  Group ftpuser
  UserAlias anonymous ftpuser
  RequireValidShell off
  MaxClients 10
  DisplayLogin welcome.msg
  <Directory *>
    <Limit READ DIRS>
      AllowAll
    </Limit>
    <Limit WRITE>
      AllowAll
    </Limit>
  </Directory>
</Anonymous>
