[global]
   server string = Linux Enterprise Lab File Server
   server role = standalone server
   map to guest = Bad User
   log file = /dev/stdout
   max log size = 0
   disable spoolss = yes
   load printers = no
   printing = bsd
   smb ports = 445 139

[public]
   path = /srv/samba/public
   browseable = yes
   read only = no
   guest ok = yes
   force user = analyst

[finance]
   path = /srv/samba/finance
   browseable = yes
   read only = no
   guest ok = no
   valid users = analyst
   force user = analyst
